### ISSUE TITLE
酒を種類ごとに識別する処理の流れについて

### ISSUE THREAD

**Issue by mitukawa** [zemi-team2/sake#13]
# 概要
酒をカメラで撮影して、どの酒であるかを分類するまでの処理の草案を記述  
  
# 処理の流れ
1.  対象となる酒を撮影  
2.  YOLOを用いて酒の容器部分のみを抽出 
3.  OCRを用いて酒の名前をテキストで取得
4.  NNに酒の名前を入力して５種類に分類

# 備考
* 2は時間があれば実装  
* 1をフロントエンド、2～4をバックエンドで実装

**Comment by watagit** [comment]
Discussions に移行しました
https://github.com/zemi-team2/sake/discussions/31
