### ISSUE TITLE
React の導入に関する議論

### ISSUE THREAD

**Issue by watagit** [zemi-team2/sake#23]
@zemi-team2/all 
フロント側の開発環境についてですが、ライブラリとして React を導入するか個人的に迷っています！
個人的に思っているメリットとデメリットを挙げます。

### メリット
- UI が圧倒的に書きやすくなる
- React に興味がある・やってみたい人が多い場合は良い機会になる

### デメリット
- 学習コストがかかる

導入する場合は Git, GitHub 同様簡単なハンズオン的な勉強会的な時間をとってもいいかなと思ってます。
みなさんの意見を聞きたいです。

**Comment by mitukawa** [comment]
自分はReact興味あります。

**Comment by watagit** [comment]
Discussions に移行しました
https://github.com/zemi-team2/sake/discussions/30
