### ISSUE TITLE
画像をサーバーに送信する処理を実装

### ISSUE THREAD

**Issue by mitukawa** [zemi-team2/sake#37]
## ✨ Summary

画像をサーバーに送信する処理を実装
## 🔥 Requirements

- #36 で作成した`upLoadImageserver`関数に画像をサーバーに送信する処理を実装する。
- ~~サーバーに送信する処理を実装するに当たって、バックエンドの環境にFlaskを導入必要がある。~~

## 📄 References

- ~~[Flaskのインストール](https://qiita.com/Daara_y/items/72f18d70a6240feb6c05)~~
- [ReactとFlaskの連携](https://qiita.com/Pu-of-Parari/items/f3733f0ba48e1df50667)

## ✅ Tasks

- [x] ~~Flaskのインストールと動作確認~~    #38 に移動
- [x] ~~画像を保存する場所を決める~~  必要なくなったため
- [x] 画像をサーバーに送信する処理を実装（フロントエンド）
- [x] 画像をサーバーに送信する処理を実装（バックエンド）

**Comment by watagit** [comment]
@mitukawa 
"Flask の導入"だけ別イシューに切り出してもいいかもです。
差分が大きくなってコードレビューのコストが上がりそうな気がしています 🤔

**Comment by mitukawa** [comment]
そうやね
Flaskの導入は別のイシューに分割します。

**Comment by watagit** [comment]
@mitukawa 
`画像をサーバーに送信する処理を実装（バックエンド）`この部分ってどこまでの実装をイメージされてますか？

**Comment by mitukawa** [comment]
画像をpostでサーバーに送信してpythonで扱えるまでを想定しています。
ＯＣＲとか、物体検知のような細部の処理は考えていません

**Comment by mitukawa** [comment]
あと、おそらく画像は保存しなくても大丈夫そうです。
