### ISSUE TITLE
jQuery の導入に伴う ESLint の設定の変更

### ISSUE THREAD

**Issue by watagit** [zemi-team2/sake#48]
## ✨ Summary

jQuery 用に ESLint の設定を変更する

## 🔥 Requirements

- `eslint-plugin-jquery`がインストールされること
- `npm run lint`を実行した際に警告が出なくなること

## 📄 References

- [eslintの設定](https://qiita.com/s-katsumasa/items/732dd084240c787c2934)

## ✅ Tasks

- [x] `eslint-plugin-jquery`のインストール
- [x] jQuery のプログラムを書いて警告が出ないことを確認する

**Comment by mitukawa** [comment]
対応ありがとう
