### ISSUE TITLE
モックの作成

### ISSUE THREAD

**Issue by watagit** [zemi-team2/sake#58]

**Comment by mitukawa** [comment]
UIのデザインを考える時にFigmaが、web上で作業出来て便利そうです。
* 参考サイト  
 [初心者向け！実例で学ぶデザインツールFigmaの使い方](https://yososhi.com/archives/figma-for-beginner/)
* 公式サイト
[figma](https://www.figma.com/?fuid=)

**Comment by watagit** [comment]
@mitukawa 
Figma 使いましょう〜！

**Comment by mitukawa** [comment]
まだ、使い方はわからないけど、初期設定だけしといたので共有しときます。
[Figma 共有リング](https://www.figma.com/file/kecsCYs4sxSNYM4DoWZ5OR/appUI?node-id=0%3A1)

**Comment by watagit** [comment]
作成済み
