### ISSUE TITLE
Vision AI 関連コードの Flask への組み込み

### ISSUE THREAD

**Issue by watagit** [zemi-team2/sake#66]
## ✨ Summary

Vision AI による分類関数を Flask に組み込む。

## 🔥 Requirements

- Vision AI による分類関数が Flask に組み込まれること

## ✅ Tasks

- [ ] 分類関数の仕様を理解する
- [ ] app.pyに分類関数をインポートして組み込む
- [ ] レイアウトを含めて動作確認を行う

**Comment by mitukawa** [comment]
## ✅ Tasks

- [] 分類関数の仕様を理解する
- [] app.pyに分類関数をインポートして組み込む
- [] レイアウトを含めて動作確認を行う
