### ISSUE TITLE
複数の端末でアクセスしたときに正しく動作しない

### ISSUE THREAD

**Issue by mitukawa** [zemi-team2/sake#74]
## 🐛 Summary

複数のアクセスが同時あった場合、`app.py`の変数`IMAGE`が上書きされて先にアクセスした方の画像データが消えてしまう不具合がありました。

## 👀 Steps

1. 1つ目の端末でアクセスして撮影して確認画面へ移動
2. 2つ目の端末でアクセスして撮影して確認画面へ移動
3. 1つ目の端末で撮影してpython上に格納したデータが2つ目に上書きされて正しく動作しない

## 🎨 Expected Behavior

1つ目のアクセスと2つ目のアクセスを独立して処理できるようにする。

## 📦️ Environment

- windows/Docker(Linux)
- Chrome 

## 💡 Solution

- 解決策１：
確認画面でも画像をPOSTする（2回サーバに送信するため無駄）
- 解決策2：
画像をアクセスごとにユニークなファイル名で保存する（ストレージを圧迫するため健全ではない）

今のところは解決策１を採用するつもりです。

## ✅ Tasks

- [x] 確認画面で画像をPOSTするように`preview.html`を変更
- [x] 確認画面で画像をPOSTするように`app.py`を変更
- [x] 動作確認

**Comment by watagit** [comment]
解決策1良きと思われます！
