### ISSUE TITLE
確認画面から撮り直しボタンを押すと、結果画面に遷移する

### ISSUE THREAD

**Issue by watagit** [zemi-team2/sake#85]
## 🐛 Summary

確認画面の撮り直しボタンを押すと、確認画面に遷移する。

## 📸 Screenshot

<img src="https://user-images.githubusercontent.com/44804976/134139843-a12fd562-d33e-4d0e-81b5-8d650d959764.gif" width="400"/>

## 👀 Steps

1. トップ画面にアクセスする
2. 写真を撮る
3. 確認画面で撮り直すボタンを押す
4. 結果画面に遷移する

## 🎨 Expected Behavior

確認画面で撮り直しボタンを押すと、トップ画面に遷移する。

## 📦️ Environment

- macOS
- Chrome

## 💡 Solution

ルーティング周りが正しくないっぽいので、調査する。

**Comment by watagit** [comment]
@mitukawa 
この挙動って満河さん想定済みだったりしますか？
バグだと思ってイシュー立てたんですが 🤔

**Comment by mitukawa** [comment]
バグやね、撮り直しボタンを`type`を`button`にすれば行けるはず、、、
``` html
<button type="button" .... />
```
