### ISSUE TITLE
デプロイ後の動作確認

### ISSUE THREAD

**Issue by watagit** [zemi-team2/sake#96]
## ✨ Summary

デプロイ後にスマホブラウザでアプリケーションが問題なく動作するか確認する

## 🔥 Requirements

- [x] トップ画面で写真撮影ができる
- [x] トップ画面で撮影した写真が確認画面に表示される
- [x] 確認画面で完了ボタンを押すと結果画面に遷移し、お酒情報が表示される

**Comment by mitukawa** [comment]
@zemi-team2/all 
今回のアプリの使用場面とは直接関係しないですが、一応共有しときます。
## 🐛 バグの内容
モニターに映った画像を近づけて撮影するとプレビュー画面で画像が読み込めなくなります。
## 🔍 試したこと
- モニターの画像を撮影する。
- プレビュー画面のimgタグのsrcを確認すると、srcにはアップロードされていました。
- srcの画像（base64）を[このサイト](https://tomari.org/main/java/base64d.html)でデコードしてもうまくいかなかったです。
- 少し遠めで撮影するとロードは長くなるけど、正しく表示されます。
## 🤔 原因
よくわからないのですが、スマホのカメラの仕様でモニターを撮影すると何かしらの補正をして、データ量が大きくなっているのかもしれないです。
